---
- name: Install LEMP Stack
  hosts: localhost
  become: True
  tasks:
     - name: Remove index.php file from lemp directory for next scenario
       file:
         path: /home/ubuntu/lamp/lemp/index.php
         state: absent
         
     - name: Stop container links with docker_compose module
       docker_compose:
        project_src: /home/ubuntu/lamp/lemp/
        state: absent
