web:
    image: nginx:alpine
    ports:
        - "80:80"
    volumes:
        - .:/code
        - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
        - mariadb
php:
    image: php:7.2-fpm
    volumes:
        - .:/code
mariadb:
    image: mariadb
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: example
